Test-shmest

## Importing data

```{r}
#| echo: false
#| output: false
#| warning: false

install.packages('pacman')
pacman::p_load(tidyverse, car, stargazer, readxl, corrplot, rms, jtools, margins, ggeffects, multcomp, readxl, zoo, lubridate, ggplot2, forecast, dplyr, tseries)
```

## Simulation

```{r}

theta1 <- 0.2
theta2 <- 0.4
sigma <- 1
delta <- 2
N <-1002

epsilon <- rnorm(n = N, mean = 0, sd = 1)
y <- numeric(N)
y[1] <- 0
y[2] <- 0

for (x in (3:N)) {
  y[x] <- delta + theta1*y[x-1] + theta2*y[x-2] + sigma*epsilon[x]
}

y <- y[3:1002]


plot(y, type = "l")

```
Mean value:
```{r}
mean(y)

```

Autocovariances

```{r}
var(y) # gamma 0
cov(y[2:1000], y[1:999]) # gamma 1
cov(y[101:1000], y[1:900]) # gamma s for s = 100
```
Autocorrelations

```{r}
acf(y,pl=FALSE)
```
```{r}
pacf(y, 5)
```

Let's compare to predicted values:










## Working with data

Deploying data

```{r}

# 6 header lines are removed
raw_data <- read_excel("CMO-Historical-Data-Monthly.xlsx", 
    sheet = "Monthly Prices", skip = 6) %>% dplyr::slice(143:nrow(raw_data))
      # As well as 143 irrelevant lines (price was fixed)
     

#need to filter DATA.
gold <- raw_data %>% dplyr::select(GOLD) 
gold$n <- 1:nrow(gold)

gold$month <- raw_data[1] %>% map(function(row) {
  make_date(
    parse_number(substring(row,1,5)),
    parse_number(substring(row,6,7)),
    1
  )
}) %>% unlist

gold$month <- as.Date(gold$month)


#gold$date <- as.Date(data$date, "%Y-%m-%d")
#data <- xts(data[,-1], order.by = data[,1])

```


```{r}
ggplot(gold, aes(x=month,y=GOLD)) +
  geom_line() +
  ggtitle("Time Series Plot") +
  xlab("Date") +
  ylab("Value")

```

```{r}
ggplot(gold, aes(x=month,y=GOLD)) +
  geom_line() +
  geom_smooth(method = "loess", size = 1.5) +
  geom_forecast(h=12) + 
  ggtitle("Time Series Plot with Moving Average and Forecast") +
  xlab("Date") +
  ylab("Value")
```

Removing linear trend

```{r}

summary <-lm(GOLD ~ n, data=gold) %>% summary
beta_n <- summary$coefficients[2]
gold$no_linear_trend = gold$GOLD - beta_n * gold$n

ggplot(gold, aes(x=month,y=no_linear_trend)) +
  geom_line() +
  ggtitle("Time Series Plot") +
  xlab("Date") +
  ylab("Value")


```
Removing moving average


```{r}
period <- 48 # months
gold$moving_average <- rollmean(gold$GOLD, k=period, fill=NA)

ggplot(gold, aes(x=month)) +
  geom_line(aes(y=GOLD), color = "navy") +
  geom_line(aes(y=as.numeric(moving_average)), color = "darkred") +
  ggtitle("Time Series Plot") +
  xlab("Date") +
  ylab("Value")

```
Removing moving average (contuation)

```{r}
pure_gold <- gold %>% na.omit
pure_gold$no_moving_average <- pure_gold$GOLD - pure_gold$moving_average
nrow(pure_gold)

ggplot(pure_gold, aes(x=month)) +
  geom_line(aes(y=no_moving_average), color = "navy") +
  geom_line(aes(y=no_linear_trend), color = "darkred") +
  ggtitle("Time Series Plot") +
  xlab("Date") +
  ylab("Value")

```

Descriptive statistics
```{r}
mean(pure_gold$no_moving_average)
sd(pure_gold$no_moving_average)

```
ACF, PACF tests

```{r}
acf(pure_gold$no_moving_average)
pacf(pure_gold$no_moving_average)

adf.test(pure_gold$no_moving_average, k=0)

```

```{r}

pure_gold$logs = log(abs(pure_gold$no_moving_average))*(pure_gold$no_moving_average/abs(pure_gold$no_moving_average))
pure_gold$first_differences = diff(pure_gold$no_moving_average) %>% append(NA)

pure_gold$gold_lagged = pure_gold$no_moving_average[2:nrow(pure_gold)] %>% append(NA)
pure_gold$logs_lagged = pure_gold$logs[2:nrow(pure_gold)] %>% append(NA)

ggplot(pure_gold, aes(x=month,y=logs)) +
  geom_line() +
  ggtitle("Time Series Plot") +
  xlab("Date") +
  ylab("Value")

ggplot(pure_gold, aes(x=month,y=first_differences)) +
  geom_line() +
  ggtitle("Time Series Plot") +
  xlab("Date") +
  ylab("Value")


```


Scatter plots of levels against their lagged counterparts

```{r}
ggplot(pure_gold, aes(x=no_moving_average,y=gold_lagged)) +
  geom_point(size=2, shape=23) +
  ggtitle("Scatterplot") +
  xlab("Actual value") +
  ylab("Lagged value")

ggplot(pure_gold, aes(x=logs,y=logs_lagged)) +
  geom_point(size=2, shape=23) +
  ggtitle("Scatterplot (logs)") +
  xlab("Actual value") +
  ylab("Lagged value")


```
```{r}
ggplot(pure_gold, aes(x=no_moving_average)) +
  geom_histogram() +
  ggtitle("Time Series Plot") +
  xlab("Date") +
  ylab("Value")

ggplot(pure_gold, aes(x=logs)) +
  geom_histogram() +
  ggtitle("Time Series Plot") +
  xlab("Date") +
  ylab("Value")


plot(density(pure_gold$no_moving_average))
plot(density(pure_gold$logs))

```

```{r}
stargazer(pure_gold, type = "text")
```







